.rubocop.yml, Gemfile, Gemfile.lock, bin/rubocop
This is the rails [rubocop.yml](https://github.com/rails/rails/blob/master/.rubocop.yml).
The only update I made is to change the `Style/StringLiterals` rule. They prefer [`double_quotes`](https://github.com/rails/rails/blob/master/.rubocop.yml#L167) and we `single_quotes`.
=> feat: add rubocop

app/views/layouts/_nav.html.erb
The logo was "clickable" (has a logo style hover state) but wasn't leading anywhere. Now it does.
=> feat: add logo link

app/models/project.rb
Using the `5-my-project-name` trick for compatibility with the existing id lookups
I didn't see automated tests, but this works in all my manual tests of get, edit, delete, highlight as expected
=> Add project name to project page URLs

app/controllers/users/registrations_controller.rb, app/models/user.rb, app/views/devise/registrations/index.html.erb
This includes a search on the volunteers' page. Only visible profiles will be shown in the search results.
This does only search by name, email, about, location and level of availability. 
In a follow-up diff, will add search by skills as well
=> Adding Basic Search in volunteers page

app/views/projects/show.html.erb
Fixes an XSS with the autolinking that happens on "How to get in touch" on Projects#show.
Given this input: `An <b>XSS test</b> <script>alert(1)</script> https://google.com foo`
=> Fix: sanitize project contact before showing it unescaped (XSS)

app/views/layouts/_head_content.html.erb, app/views/projects/show.html.erb
Currently, sharing a specific project page on twitter or facebook, will actually link to the homepage instead.  This pull request should allow social shares (twitter or facebook) of a project page to go directly to that project's specific page.
**Please note that I am not a ruby developer so I am not 100% sure the call to project_url() will output the correct hostname in production.**  
On the development environment I was able to cobble together, the URLs it generated did contain the schema, hostname, and port, e.g.
`http://localhost:3000/projects/1-this-is-a-test`
My expectation is that in production `http://localhost:3000/` will be replaced with `https://www.helpwithcovid.com/` automatically.  If that is not the case please do not merge this pull request.
=> Allow social shares to go directly to that project's specific page instead of the homepage

app/controllers/projects_controller.rb, app/helpers/application_helper.rb, app/views/devise/registrations/_user.html.erb, app/views/devise/registrations/show.html.erb, app/views/partials/_filter-badge.html.erb, app/views/partials/_skill_badges.html.erb, app/views/projects/_project.html.erb, app/views/projects/show.html.erb
This  adds "Skill Types" list above "Project Types" on the Project cards 
Also:
* adds `title` attribute to "and X more" element
* use 'blue' for "Skill Types" to differentiate from "Project Type" indigo.
* some small refactoring
=> Adds list of skills needed to each project card on listing.

app/views/devise/registrations/index.html.erb
Just an idea! Take it or leave it:
=> Show user count on volunteer page

app/models/project.rb, app/models/user.rb
The search is now and. It will show better results. 
All the words in search now must match in the project. If all the words occur across multiple places in the project(title, description, etc), it will be still be considered as a match.
=> Making the search and

app/frontend/packs/stylesheets.css, app/helpers/application_helper.rb, app/views/devise/registrations/_user.html.erb, app/views/devise/registrations/show.html.erb, app/views/partials/_skill_badges.html.erb, app/views/projects/_project.html.erb, app/views/projects/show.html.erb, tailwind.config.js
I am proposing a slight change in how we show the skills and project types on the homepage. Right now the tags get justified weird in certain screen sizes.
1. Have labels for both tag "clouds" (project type and skils needed)
2. Collapse the tag clouds when on mobile
Because we are moving the skills tags from the right on mobile to the left on desktop, we need to change the alignment of each tag. To be more precise the margin from the left to the right. At the moment we're doing that with ruby code that isn't aware of the responsive changes. We may set it to the right or to the left on runtime and that's it.
I added a tailwind plugin that adds spacer utilities (`.space-x-right-4`, .md:space-y-bottom-2, etc.) that space the children elements and allow us to change the spacing direction …
=> feat: new project index tags proposal

app/controllers/projects_controller.rb, app/models/project.rb, spec/controllers/projects_controller_spec.rb
Allows JSON export of projects to `Projects#index` and `Projects#show` by returning this data from each one (unpaginated):
```
{
"id":2,
"name":"OpenCrisisBoard project",
"description":"\r\nOpenCrisisBoard is an open-source ready-to...",
"participants":"Our team previously worked on the Ebola response and ...",
"looking_for":"We need help with:\r\n- develop...",
"created_at":"2020-03-21T13:59:35.325Z",
"updated_at":"2020-03 21T15:34:13.817Z",
"location":"remote",
"contact":"",
"highlight":true,
"progress":"",
"docs_and_demo":"",
"number_of_volunteers":"",
"to_param":"2-opencrisisboard-project", 
"volunteered_users_count":0,
"project_type_list":["Mental health","Map volunteers to needs","Medical equipments","Track the outbreak"],
"skill_list":["PM","Software"]}
}
```
Fixes #35
=> Add json response to ProjectsController#index and #show

app/views/devise/registrations/index.html.erb, app/views/projects/index.html.erb, db/schema.rb
With so many volunteers and projects, it'll be more convenient to also put pagination on the top instead of having to scroll all the way to the bottom to click next page.
=> Added pagination to top too

app/helpers/application_helper.rb
As far as I can see the the bad link (https://helpwithcovid.com/projects?skill=Software&amp) isn't generated from us. I couldn't find it anyway. The user agent is a wordpress site. 
So my hunch is that another site generated that badly encoded link and people click on it.
I've pushed a fix to strip it anyway.
=> fix: bad encoded params

app/controllers/projects_controller.rb, app/views/projects/_project.html.erb
* fixes the `.includes` in ProjectsController (AR query methods don't mutate the caller)
* prefer `foobars.map(&:name)` over `foobar_list` readers to fix N+1s (according to the PR discussions in `acts_as_taggable`, the `_list` methods don't work with preloading).
This probably won't make much of a difference, but I'd be super curious if it's noticeable!
=> Fix project_types and skills N+1 queries on Projects#index.

README.md, app/mailers/project_mailer.rb, app/views/layouts/application.html.erb, app/views/projects/show.html.erb, config/environments/production.rb, config/initializers/admins.rb
These changes allow other forks of this project to more easily adapt email addresses to their team. It allows to configure:
- the email address used as `reply-to` and which is displayed on the homepage
- the email address(es) receiving technical errors
- the accounts with admin permissions
To retain your configuration, you would need to set the following environment variables on Heroku:
| Variable | Value |
|------------|---------|
| `EMAIL_ADDRESS` | `helpwithcovid@gmail.com` |
| `EXCEPTION_NOTIFIERS` | `radu.spineanu@gmail.com` |
| `ADMINS` | `radu.spineanu@gmail.com,liamjweld@gmail.com,joe@marsbio.vc,tinneipang@gmail.com` |
=> Configuration via environment variables

.env.test, Gemfile, config/application.rb
Add `.env.test` as a copy of `.env.sample`... keeping these in sync might suck but seemed cleaner than alternatives on first glance
=> Fix build by loading dotenv in test mode

app/views/home/about.html.erb, app/views/layouts/application.html.erb
Someone asked me for the link and I realized it's not on the site
Feedback on placement and copy welcome
Looks like this in footer:
And on the /about page:
=> Add links to the GitHub repository in the footer and /about page

app/controllers/projects_controller.rb, app/frontend/covid/covid.js, app/frontend/covid/new_project.js, app/frontend/covid/project_form.js, app/models/project.rb, app/views/projects/_project_form.html.erb, app/views/projects/show.html.erb, db/migrate/20200401143158_accepting_volunteers.rb, db/schema.rb, spec/controllers/projects_controller_spec.rb, spec/models/project_spec.rb, spec/rails_helper.rb
Started a PR for #107 
Changelog
- Added `accepting_volunteers` boolean 
- Added checkbox to `new/edit` forms. Also added JS to hide relevant fields if you arent actually needing volunteers.
- Same fields get hidden on `show` page if you uncheck volunteers.
- Added query string filter for `project#index`. Will expose in the view at some later point.
- Wrote tests for all of the above and added some missing specs
=> Added "accepting_volunteers" checkbox to projects

app/frontend/covid/project_form.js, app/models/project.rb, app/models/user.rb, app/views/projects/_project.html.erb, app/views/projects/_project_form.html.erb, app/views/projects/show.html.erb, db/seeds.rb, spec/controllers/projects_controller_spec.rb, spec/factories.rb, spec/models/project_spec.rb, spec/models/user_spec.rb
- Switched to radio buttons per @sradu's suggestion. Much nicer.
- Minor copy changes
- Started to fill out `seeds.rb` so that `rails db:setup` prepopulates with some data.
- Added basic tests for project name validation and creation
- If `accepting_volunteers?==true` then in order to volunteer for a project, a user must have a skill that matches the list of skills required for a project. If you don't match, you will see this button:
and if you click the button, it will say
=> Accepting volunteers radio buttons

app/views/home/index.html.erb
Some are resources, some are past events, some are
future events. It's a variety really
=> Rename the "Upcoming HWC Events" block on homepage

app/controllers/projects_controller.rb, app/views/home/_project-group.html.erb
The "See all X projects" is sending the user on a filter that has actually less than X projects. The link query count is made by using the `any: true` param and the actual page query is not using it.
Fixed that by adding a hidden `any=true` filter.
=> fix: project-group-query-any-project

.circleci/config.yml, README.md
This PR addresses [issue 144](https://github.com/helpwithcovid/covid-volunteers/issues/143) by adding rubocop to the circleci build steps.
I have checked that my changes to `config.yml` are valid using the circleci CLI tool.
=> Add rubocop step to circleci config

app/views/projects/_project_form.html.erb
If you select "No, I don't need any volunteers," this
volunteer_location field is not visible and the javascript
error-checking blocks submitting the form.
If you switch to "yes" and put in a value in, then switch
back to "no" it works again.
=> Temporary hotfix for broken "Create project" flow

app/views/devise/registrations/show.html.erb, app/views/projects/show.html.erb
Closes #162
Also. added link support to `@project.short_description` and `@project.description` blocks, but could remove those if those were excluded on purpose.
=> Fix: Add rel="nofollow noopener noreferrer" to outbound links

app/frontend/styles/application.css, app/views/projects/_project-card.html.erb
Fixes #145 
Refined the spacing and sizing overall in the project card component.
I added a scroll affordance gradient on the card label component (it appears slightly over labels that do not scroll if last label's edge is right at the edge of the container—would require some JS to show gradient only if elements extended past right edge).
I rearranged the elements on the bottom of the cards to accommodate situations where the location or the updated info was wrapping.
**Project Cards on Homepage - Before and After**
**Project Card - Before and After**
=> Refines project card styles

app/controllers/application_controller.rb, app/controllers/projects_controller.rb, app/controllers/users/registrations_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, db/seeds.rb, spec/controllers/projects_controller_spec.rb, spec/controllers/users/registrations_controller_spec.rb, spec/helpers/application_helper_spec.rb
* Log events for user creation, project creation and volunteering
* Track 'start' and 'complete' events separately so we can look at the funnel
* Uses Rails session to push and pop the action name
* Uses one 'Actions' GA category for simplicity
* Always load GA javascript code, no matter the environment, but use a new GA property that I setup just for dev/test. This is so we don't accidentally break production. 
Would love some eyes on this, particularly if anyone cares about my overly verbose event names. I don't totally love the session-based approach but it is reliable.
fixes #117
=> Basic Google Analytics event tracking

app/controllers/projects_controller.rb
While we're linting things... no more of this in the test suite output:
```
DEPRECATION WARNING: #current_per_page is deprecated and will be removed in the next major version. Please use #limit_value instead.
```
To confirm:
```
bundle exec rake && bundle exec rubocop && echo 'All is good' || echo 'You broke something'
```
=> Fix will_paginate deprecation warning

spec/controllers/home_controller_spec.rb
These random failures caused by the literal use of RANDOM()
Easiest solution here is just forcibly clearing out all existing projects
I also explicitly left a comment in this test so future generations will understand
why that's there, since it's counter-intuitive
=> Fix random home#index test failures

spec/controllers/admin_controller_spec.rb, spec/controllers/home_controller_spec.rb, spec/controllers/offers_controller_spec.rb, spec/controllers/projects_controller_spec.rb, spec/models/offer_spec.rb, spec/models/project_spec.rb, spec/models/user_spec.rb, spec/models/volunteer_spec.rb
This just introduces the FactoryBot shorthand, allowing us to replace...
`FactoryBot.create(:some_factory)`
with
`create(:some_factory)`
=> Use FactoryBot shorthand to save typing strokes.

.circleci/config.yml
Addresses comment from Discord: https://discordapp.com/channels/689552739797434432/689658307392307306/700117137012031589
Currently our Circle CI setup runs one long job which does many things in consecutive order:
- build the app
- run tests
- run rubocop
This PR sets up circle ci to use its '[workflows](https://circleci.com/docs/2.0/workflows/)' feature. Using workflows, we can split out the one big all-encompassing job into seperate jobs for each thing listed above.
I've also noticed that we currently run rubocop after we've finished tests. I've setup workflows to run these two jobs in parallel as I don't think one depends on the other. This could speed delployment 🤞🏾
=> Setup circle ci config to use workflows

spec/factories.rb, spec/models/user_spec.rb
I've refactored tests to correctly use `let` and `context` blocks to avoid code duplication and overly long `it` blocks.
I've also added the `skill_set` attribute to the `:user_complete_profile` factory, as this was made a required profile field in a [previous PR](https://github.com/helpwithcovid/covid-volunteers/pull/159).
=> Refactor tests and add skill_set to factory :user_complete_profile

spec/controllers/offers_controller_spec.rb, spec/models/offer_spec.rb
This PR adds tests for each action in the OffersController.
For each action I've tested:
- authorized and unauthorized requests 
- that global announcements are not visible
Additionally, for `edit`, `update` and `destroy` I've tested that admins have access.
I've also moved one test to the `Offer` model spec as it tested a method on that model.
I have not tested changes to the db as I wasn't sure how to in this spec (plus I wasn't sure if it was necessary - still figuring out which tests sit inside the controller spec domain 🙂)
=> Finish offer controller spec

app/frontend/styles/featured-categories.css, app/views/projects/_project-card.html.erb
Fixes #194 
Removes quick and clever CSS (always gets me eventually!) in favor of a more resilient HTML structure and simple Tailwind classes. 
The issue was that `position: fixed` really doesn't play well with iOS Safari at all—and I completely forgot.
=> refactor project card scroll gradient for ios compatibility

app/views/projects/_project-card.html.erb
Fixes #153 
Restructures the bottom of the card layout so the time-ago is nested under volunteer info when location wraps to two lines.
(Note: this is the only country name where the second line is long enough to extend under the location icon—it looks awkward here but is an extreme corner case)
=> refactor project card layout to fix details spacing

app/frontend/covid/covid.js
After clicking select all on the countries filter, only global was getting selected. This fixes that.
=> fix: countries filter is not selecting all countries

app/views/partials/_featured-projects.html.erb
=> fix: featured projects icon is misaligned

app/views/projects/show.html.erb
Fixing the issue related to useful links shortening
Eg: https://helpwithcovid.com/projects/833-humanner
Updated fix looks like this
=> Fixing issue related to description link

spec/models/project_spec.rb
We were previously testing the return value of this line in the `Project` model within its `cover_photo` method:
`ActionController::Base.helpers.asset_pack_path "media/images/#{filename}-default.png"`
As we do not have control over the inner workings of `ActionController::Base.helpers.asset_pack_path`, only the parameter that we feed it, this PR changes the spec to test the parameter we give to `ActionController::Base.helpers.asset_pack_path`
cc @jamiew
=> Test correct calling of asset_pack_path instead of testing its return value

app/controllers/users/registrations_controller.rb, spec/controllers/users/registrations_controller_spec.rb, spec/factories.rb
Addresses https://github.com/helpwithcovid/covid-volunteers/issues/244
cc pairing buddy: @cooknat
When a user is on a page (eg '/projects') and then they go to their profile page and edit it, when they hit save changes, they are taken back to the last page they were on (in this case '/projects')
=> Redirect to previous page after profile edit
